version: 2

project_name: aethercli

before:
  hooks:
    - go mod tidy

builds:
  - id: aethercli
    main: ./cmd/aethercli
    binary: aethercli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Aculnaj/aethercli/internal/commands.Version={{ .Version }}

archives:
  - id: default
    ids:
      - aethercli
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
